# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1dd8f69a2540ae03061b3857dfc2aebae22797e8210fd54472d5ec90e2efcc78c0a7d6e4477f618660238462087028a4f447c50633cdde36239371b60b075cfa

test:
  secret_key_base: fffe6d6676aa16eb53e160ecf28833b18960fd9b7eb9011beba2278319242eca2404b1f93280d80b8fb467968b1a0fbc07b329c861e476a587cd3c96f5164cc3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
